# Generated by Django 3.0.4 on 2020-04-15 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200415_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 14, 7, 34, 815183, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
