# Generated by Django 3.0.4 on 2020-04-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200415_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='updated',
        ),
    ]
