# Generated by Django 3.0.4 on 2020-04-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtitulos'),
        ),
    ]
