# Generated by Django 3.0.4 on 2020-04-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200415_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='update',
            new_name='updated',
        ),
    ]
